name: test_app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  auto_route: ^7.8.3
  bloc: ^8.1.2
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.7
  json_serializable: ^6.7.1
  retrofit: ^4.0.1

dev_dependencies:
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mask_text_input_formatter: ^2.5.0
  retrofit_generator: ^7.0.8

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/pics/

  fonts:
    - family: SF-Pro-Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display.ttf
